<?php
/**
 * Created by PhpStorm.
 * User: Комрад
 * Date: 01.08.2019
 * Time: 15:04
 */

namespace tcbQB\QueryBuilder\Syntax;


use tcbQB\QueryBuilder\AbstractQuery;

class On extends AbstractQuery
{
    use WhereForSelectTrait;


    public function __construct($first_row,$second_row,$query)
    {
        $this->query=$query;
        $this->query.="ON $first_row=$second_row ";
    }

    public function get()
    {
        $this->query = substr_replace($this->query,"",-1);
        return parent::get(); // TODO: Change the autogenerated stub
    }

}