<?php
/**
 * Created by PhpStorm.
 * User: Комрад
 * Date: 03.07.2019
 * Time: 2:05
 */

namespace QueryBuilder\Syntax;
require_once PROJECT_PATH."/QueryBuilder/AbstractQuery.php";

use QueryBuilder\AbstractQuery;

class OrderBy extends AbstractQuery
{
    public function __construct($query)
    {
        $this->query=$query."ORDER BY ";
    }

    public function asc($column)
    {
        $this->query=$this->query.$column." ASC,";
        return $this;
    }

    public function desc($column)
    {
        $this->query=$this->query.$column." DESC,";
        return $this;
    }

    public function get()
    {
        $this->query=substr_replace($this->query,' ',-1);
        return parent::get(); // TODO: Change the autogenerated stub
    }

}