<?php

namespace tcb\QueryBuilder\Syntax;

use tcb\QueryBuilder\AbstractQuery;

class OrderBy extends AbstractQuery
{
    public function __construct($query)
    {
        $this->query=$query."ORDER BY ";
    }

    public function asc($column)
    {
        $this->query.=$column." ASC,";
        return $this;
    }

    public function desc($column)
    {
        $this->query.=$column." DESC,";
        return $this;
    }

    public function get()
    {
        $this->query=substr_replace($this->query,'',-1);
        return parent::get(); // TODO: Change the autogenerated stub
    }

}